name: Notify Discord

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"🚀 Có commit mới được push lên repo\"}"